const languages = {
  en: {
    labelAirport: "Where are you flying from?",
    labelFirstDate: "Arrival Date at Parking",
    labelSecondDate: "Departure Date from Parking",
    placeholderAirport: "Click and select an airport",
    placeholderDate: "Select a date",
    sendBtn: "Search for Parking",
    doneBtn: "Done",
    listOfAirports: [
      { id: 1, code: "WAW", title: "Chopin Airport Warsaw Okęcie" },
      { id: 2, code: "WMI", title: "Warsaw Modlin Airport" },
      { id: 3, code: "KTW", title: "Katowice Pyrzowice Airport" },
      { id: 4, code: "KRK", title: "Krakow Balice Airport" },
      { id: 5, code: "GDN", title: "Gdansk Airport" },
      { id: 6, code: "WRO", title: "Wroclaw Strachowice Airport" },
      { id: 7, code: "POZ", title: "Poznan Lawica Airport" },
    ],
  },
  pl: {
    labelAirport: "Skąd wylatujesz?",
    labelFirstDate: "Data przyjazdu na parking",
    labelSecondDate: "Data wyjazdu z parkingu",
    placeholderAirport: "Kliknij i wybierz lotnisko",
    placeholderDate: "wybierz datę",
    sendBtn: "Szukaj Parkingu",
    doneBtn: "Gotowy",
    listOfAirports: [
      { id: 1, code: "WAW", title: "Chopina Warszawa Okęcie" },
      { id: 2, code: "WMI", title: "Warszawa Modlin" },
      { id: 3, code: "KTW", title: "Katowice Pyrzowice" },
      { id: 4, code: "KRK", title: "Kraków Balice" },
      { id: 5, code: "GDN", title: "Gdańsk" },
      { id: 6, code: "WRO", title: "Wrocław Strachowice" },
      { id: 7, code: "POZ", title: "Poznań Ławica" },
    ],
  },
};
